// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TgReminderBot.Data;

#nullable disable

namespace TgReminderBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            // внутри BuildModel(ModelBuilder modelBuilder)
            modelBuilder.Entity("TgReminderBot.Models.AccessOptions", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<bool>("WhitelistEnabled")
                    .HasColumnType("INTEGER");

                b.Property<DateTimeOffset>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");
                b.ToTable("AccessOptions");
            });

            modelBuilder.Entity("TgReminderBot.Models.AccessRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Mode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Target")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TargetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Target", "TargetId");

                    b.ToTable("AccessRules");
                });

            modelBuilder.Entity("TgReminderBot.Models.ChatSettings", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ControlThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DefaultReminderThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ChatId");

                    b.ToTable("ChatSettings");
                });

            modelBuilder.Entity("TgReminderBot.Models.Reminder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NoPreview")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cron")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParseMode")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemindOffsets")
                        .HasColumnType("TEXT");

                    b.Property<string>("RunAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ThreadId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChatId", "CreatedBy");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("TgReminderBot.Models.UserSettings", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
